### ISSUE TITLE
Types of RGB TIFF files CellCatcher will accept

### ISSUE THREAD

**Issue by Svidro** [Mitogenie/CeMiA#1]
Hi! I have been able to successfully test out the CellCatcher software on the demo images, so thank you for including those. None of our images worked, so I might have given up there without a working sample!

That said, the description for CellCatcher inputs is "standard 2D RGB TIFF" files, which... I mean, there really is no such thing :) So, my question is, _how were the included sample TIFF files created and how could I replicate them_?

I have 2 color TIFF files that are RGB composite, and show up in FIJI looking very similar to the test images. Both are composite, show up as RGB, and have the channels in that order. However, I can only get the nuclear detection in CellCatcher to work when I change the order of channels so that blue is first, making a BGR image. Otherwise, CellCatcher tries to use the red channel.

The metadata indicates that there are a few differences, the most obvious were LittleEndian vs BigEndian encoding, and while SizeC=3 (and both T and Z are 1) for both tif images, the metadata for the provided test images also includes a "Channels = 3" in addition to the regular channel field being set to 3. I am guessing this second Channels field is what is causing the problems - does that mean anyone wanting to use CellCatcher will need to manually edit their TIFF files to add that field?

I also tested two RGB TIF files that are provided with FIJI in File->Open Samples (HeLa cells.tif and Fluorescent cells.tif, both IF microscopy images of cells), and both of those failed as well, so there is something very different between what is considered standard TIFF here and standard TIFF in ImageJ/FIJI. I was trying to see if it was something specific I was doing wrong with the TIFF files I had created (and attached).

Do you have any suggestions for how to convert the files, or do I need to start messing around with manually editing the metadata (have usually relied on adjusting the Properties in FIJI, so have not tried directly coding anything like that yet).
I have included a test file that only opened the original 2channel CZI in FIJI, converted it to a composite image, and then saved it as a TIFF. I could also start with the CZI file if you can suggest a workflow that is better from that starting point.

[TestFile.zip](https://github.com/Mitogenie/Mito-Hacker/files/5805649/TestFile.zip)

Please let me know if I was unclear about anything, writing this out at the end of the day after struggling for quite a bit of the day with getting the image above to work! I may also try posting on the Image.SC forum to see if anyone there has any ideas for which metadata might be causing the problem, as most of the image conversion is done through FIJI.

Side note, it looks like the link on the main MitoHacker page to the workflow image is broken.
![image](https://user-images.githubusercontent.com/23145209/104391630-24706b00-54f5-11eb-82d1-b6fb45bd8248.png)

**Comment by Mitogenie** [comment]
Hello,
Thanks for sharing your files. Once we get a chance, we will take a look at your sample images to figure out what is going wrong with the code. Once we have any updates we will let you know.
Also, the link for the flowchart is fixed! thanks for bringing that up!

**Comment by Mitogenie** [comment]
HI Svidro,
We got a chance to look at your images. And I am glad to say that your images work perfectly fine with MitoHacker.
As the description of the Cell Catcher says, you need standard RGB images for Cell Catcher. In order to export your images as RGB in Fiji (ImageJ) go to Image>Type>RGB Color
Save your images, and import them in MitoHacker. We tested your images, and I have attached the screenshots for your reference. Please let us know if you have any further questions.
![nuclei](https://user-images.githubusercontent.com/59698082/108148769-7df12a00-709f-11eb-9f35-cda1bc7daa9e.png)
![cells](https://user-images.githubusercontent.com/59698082/108148836-a0834300-709f-11eb-99a5-2dbae2d347b2.png)
![mitochondria](https://user-images.githubusercontent.com/59698082/108148896-c3155c00-709f-11eb-99ad-0770b9fb5eb7.png)
