### ISSUE TITLE
"neighbors" flag deprecated in skimage starting 18.0

### ISSUE THREAD

**Issue by emmanuel-contreras** [Mitogenie/CeMiA#2]
Great tool! I've been playing around with it the past couple of days. I ran into some problems running it originally because of the reason stated above, and jupyter output errors weren't helpful.

I updated `neighbors=8` to `connectivity=2` and it appears to be working fine. Just thought I'd let you know if you wanted to update the code or tell people to use version 17.0 or lower of skimage.

https://github.com/emmanuel-contreras/Mito-Hacker/commit/41df6b44b9aad64b3fee2da2578bbccff0381be1

https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.label

**Comment by Mitogenie** [comment]
Thanks for bringing the issue up and fixing it. 
We understand that Jupyter errors are not so helpful, but we intentionally made them look less scary.
We are glad you have a good experience. 
By the way, if you are interested, you can send us an email to mitogenie.uva@gmail.com, and we can discuss potential testing of some new codes if you are interested.
