### ISSUE TITLE
'Something is not right! Try another image.'

### ISSUE THREAD

**Issue by Lsuss** [Mitogenie/CeMiA#3]
Hello

I am trying to use cell_catcher and neither the included sample images or my own progress pass In [6]: nuc_mask = [].
All images result in 'Something is not right! Try another image.' There are also no output files. 

I have verified that my files are 2d RGB Tif files. 

Any help would be appreciated

**Comment by Mitogenie** [comment]
Hi Lsuss. Thanks for reaching out.
Cell Catcher is now part of the Mitogenie platform.
Please try the online version of Cell Catcher. If the problem persists, please send an email with a couple of example images to hello@mitogenie.com. They will be able to help you.
Thanks.

**Comment by Lsuss** [comment]
how do i get to the mitohacker on the mitogenie platform?

**Comment by Mitogenie** [comment]
MitoHacker is a set of three independent tools: Cell Catcher, Mito Catcher,
and MiA.
Each of these apps is available as a standalone fully-graphical app in
Mitogenie, which can be installed in the App Market:
 https://mitogenie.com/market/
Also, you can find all the information you need in the Academy:
https://mitogenie.com/academy/
If you have further questions about Mitogenie, you should contact
Mitogenie support at ***@***.***
Thanks
