### ISSUE TITLE
Analysis on live cell images: Without nuclei staining  

### ISSUE THREAD

**Issue by kvshams** [Mitogenie/CeMiA#4]
Thanks for the nice tool. Is it possible to analyze cells without a nuclei straining?.

Thanks,
Shams

**Comment by Mitogenie** [comment]
Hi, You can use Nuc Adder to add synthetic nuclei to your images, and then use them with Mito Hacker tools.
Just for your information, all the Mito Hacker tools (except Nuc Adder) are available on Mitogenie (https://mitogenie.com)
You may contact hello@mitogenie.com for any questions you may have regarding Mitogenie tools.
